const PageActionTypes  = {
    FETCH_PAGE_START: 'FETCH_PAGE_START',
    FETCH_PAGE_SUCCESS: 'FETCH_PAGE_SUCCESS',
    FETCH_PAGE_FAILURE: 'FETCH_PAGE_FAILURE',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE'
};

export default PageActionTypes;